name: Update airport data

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install
      - name: Generate up-to-date airport data
        env:
          DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
        run: npm run generate-airports
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add latest airport data from Duffel
          file_pattern: data/airports.json
