name: Update aircraft data

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install
      - name: Generate up-to-date aircraft data
        env:
          DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
        run: npm run generate-aircraft
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add latest aircraft data from Duffel
          file_pattern: data/aircraft.json
